source 'https://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'rake'
gem 'appium_lib'
gem 'pry'
gem 'faker'
gem 'selenium-webdriver'
gem 'cpf_faker'
gem 'httparty'
gem 'chromedriver-helper'
gem 'site_prism'
